### ISSUE TITLE
evaluate

### ISSUE THREAD

**Issue by Timaces** [hkust-vgd/riconv#1]
hi, my friends. Thank you for your work!
I want to know if have write the  evaluate code? if yes,please share it.

**Comment by cszyzhang** [comment]
There is eval_one_epoch function in the train_val_cls.py and train_val_seg.py. You can use it for evaluation.

**Comment by Timaces** [comment]
but  in test the seg,it will generate the seg picture.if the train_val_seg.py code can achieve?
